
import { Surah } from './types';

export const SURAHS: Surah[] = [
  { id: 1, name: "الفاتحة", transliteration: "Al-Fatihah", versesCount: 7 },
  { id: 2, name: "البقرة", transliteration: "Al-Baqarah", versesCount: 286 },
  { id: 3, name: "آل عمران", transliteration: "Ali 'Imran", versesCount: 200 },
  { id: 4, name: "النساء", transliteration: "An-Nisa'", versesCount: 176 },
  { id: 5, name: "المائدة", transliteration: "Al-Ma'idah", versesCount: 120 },
  { id: 6, name: "الأنعام", transliteration: "Al-An'am", versesCount: 165 },
  { id: 7, name: "الأعراف", transliteration: "Al-A'raf", versesCount: 206 },
  { id: 8, name: "الأنفال", transliteration: "Al-Anfal", versesCount: 75 },
  { id: 9, name: "التوبة", transliteration: "At-Tawbah", versesCount: 129 },
  { id: 10, name: "يونس", transliteration: "Yunus", versesCount: 109 },
  { id: 11, name: "هود", transliteration: "Hud", versesCount: 123 },
  { id: 12, name: "يوسف", transliteration: "Yusuf", versesCount: 111 },
  { id: 13, name: "الرعد", transliteration: "Ar-Ra'd", versesCount: 43 },
  { id: 14, name: "إبراهيم", transliteration: "Ibrahim", versesCount: 52 },
  { id: 15, name: "الحجر", transliteration: "Al-Hijr", versesCount: 99 },
  { id: 16, name: "النحل", transliteration: "An-Nahl", versesCount: 128 },
  { id: 17, name: "الإسراء", transliteration: "Al-Isra'", versesCount: 111 },
  { id: 18, name: "الكهف", transliteration: "Al-Kahf", versesCount: 110 },
  { id: 19, name: "مريم", transliteration: "Maryam", versesCount: 98 },
  { id: 20, name: "طه", transliteration: "Ta-Ha", versesCount: 135 },
  { id: 21, name: "الأنبياء", transliteration: "Al-Anbiya'", versesCount: 112 },
  { id: 22, name: "الحج", transliteration: "Al-Hajj", versesCount: 78 },
  { id: 23, name: "المؤمنون", transliteration: "Al-Mu'minun", versesCount: 118 },
  { id: 24, name: "النور", transliteration: "An-Nur", versesCount: 64 },
  { id: 25, name: "الفرقان", transliteration: "Al-Furqan", versesCount: 77 },
  { id: 26, name: "الشعراء", transliteration: "Ash-Shu'ara'", versesCount: 227 },
  { id: 27, name: "النمل", transliteration: "An-Naml", versesCount: 93 },
  { id: 28, name: "القصص", transliteration: "Al-Qasas", versesCount: 88 },
  { id: 29, name: "العنكبوت", transliteration: "Al-'Ankabut", versesCount: 69 },
  { id: 30, name: "الروم", transliteration: "Ar-Rum", versesCount: 60 },
  { id: 31, name: "لقمان", transliteration: "Luqman", versesCount: 34 },
  { id: 32, name: "السجدة", transliteration: "As-Sajdah", versesCount: 30 },
  { id: 33, name: "الأحزاب", transliteration: "Al-Ahzab", versesCount: 73 },
  { id: 34, name: "سبأ", transliteration: "Saba'", versesCount: 54 },
  { id: 35, name: "فاطر", transliteration: "Fatir", versesCount: 45 },
  { id: 36, name: "يس", transliteration: "Ya-Sin", versesCount: 83 },
  { id: 37, name: "الصافات", transliteration: "As-Saffat", versesCount: 182 },
  { id: 38, name: "ص", transliteration: "Sad", versesCount: 88 },
  { id: 39, name: "الزمر", transliteration: "Az-Zumar", versesCount: 75 },
  { id: 40, name: "غافر", transliteration: "Ghafir", versesCount: 85 },
  { id: 41, name: "فصلت", transliteration: "Fussilat", versesCount: 54 },
  { id: 42, name: "الشورى", transliteration: "Ash-Shura", versesCount: 53 },
  { id: 43, name: "الزخرف", transliteration: "Az-Zukhruf", versesCount: 89 },
  { id: 44, name: "الدخان", transliteration: "Ad-Dukhan", versesCount: 59 },
  { id: 45, name: "الجاثية", transliteration: "Al-Jathiyah", versesCount: 37 },
  { id: 46, name: "الأحقاف", transliteration: "Al-Ahqaf", versesCount: 35 },
  { id: 47, name: "محمد", transliteration: "Muhammad", versesCount: 38 },
  { id: 48, name: "الفتح", transliteration: "Al-Fath", versesCount: 29 },
  { id: 49, name: "الحجرات", transliteration: "Al-Hujurat", versesCount: 18 },
  { id: 50, name: "ق", transliteration: "Qaf", versesCount: 45 },
  { id: 51, name: "الذاريات", transliteration: "Adh-Dhariyat", versesCount: 60 },
  { id: 52, name: "الطور", transliteration: "At-Tur", versesCount: 49 },
  { id: 53, name: "النجم", transliteration: "An-Najm", versesCount: 62 },
  { id: 54, name: "القمر", transliteration: "Al-Qamar", versesCount: 55 },
  { id: 55, name: "الرحمن", transliteration: "Ar-Rahman", versesCount: 78 },
  { id: 56, name: "الواقعة", transliteration: "Al-Waqi'ah", versesCount: 96 },
  { id: 57, name: "الحديد", transliteration: "Al-Hadid", versesCount: 29 },
  { id: 58, name: "المجادلة", transliteration: "Al-Mujadilah", versesCount: 22 },
  { id: 59, name: "الحشر", transliteration: "Al-Hashr", versesCount: 24 },
  { id: 60, name: "الممتحنة", transliteration: "Al-Mumtahanah", versesCount: 13 },
  { id: 61, name: "الصف", transliteration: "As-Saff", versesCount: 14 },
  { id: 62, name: "الجمعة", transliteration: "Al-Jumu'ah", versesCount: 11 },
  { id: 63, name: "المنافقون", transliteration: "Al-Munafiqun", versesCount: 11 },
  { id: 64, name: "التغابن", transliteration: "At-Taghabun", versesCount: 18 },
  { id: 65, name: "الطلاق", transliteration: "At-Talaq", versesCount: 12 },
  { id: 66, name: "التحريم", transliteration: "At-Tahrim", versesCount: 12 },
  { id: 67, name: "الملك", transliteration: "Al-Mulk", versesCount: 30 },
  { id: 68, name: "القلم", transliteration: "Al-Qalam", versesCount: 52 },
  { id: 69, name: "الحاقة", transliteration: "Al-Haqqah", versesCount: 52 },
  { id: 70, name: "المعارج", transliteration: "Al-Ma'arij", versesCount: 44 },
  { id: 71, name: "نوح", transliteration: "Nuh", versesCount: 28 },
  { id: 72, name: "الجن", transliteration: "Al-Jinn", versesCount: 28 },
  { id: 73, name: "المزمل", transliteration: "Al-Muzzammil", versesCount: 20 },
  { id: 74, name: "المدثر", transliteration: "Al-Muddaththir", versesCount: 56 },
  { id: 75, name: "القيامة", transliteration: "Al-Qiyamah", versesCount: 40 },
  { id: 76, name: "الإنسان", transliteration: "Al-Insan", versesCount: 31 },
  { id: 77, name: "المرسلات", transliteration: "Al-Mursalat", versesCount: 50 },
  { id: 78, name: "النبأ", transliteration: "An-Naba'", versesCount: 40 },
  { id: 79, name: "النازعات", transliteration: "An-Nazi'at", versesCount: 46 },
  { id: 80, name: "عبس", transliteration: "Abasa", versesCount: 42 },
  { id: 81, name: "التكوير", transliteration: "At-Takwir", versesCount: 29 },
  { id: 82, name: "الانفطار", transliteration: "Al-Infitar", versesCount: 19 },
  { id: 83, name: "المطففين", transliteration: "Al-Mutaffifin", versesCount: 36 },
  { id: 84, name: "الانشقاق", transliteration: "Al-Inshiqaq", versesCount: 25 },
  { id: 85, name: "البروج", transliteration: "Al-Buruj", versesCount: 22 },
  { id: 86, name: "الطارق", transliteration: "At-Tariq", versesCount: 17 },
  { id: 87, name: "الأعلى", transliteration: "Al-A'la", versesCount: 19 },
  { id: 88, name: "الغاشية", transliteration: "Al-Ghashiyah", versesCount: 26 },
  { id: 89, name: "الفجر", transliteration: "Al-Fajr", versesCount: 30 },
  { id: 90, name: "البلد", transliteration: "Al-Balad", versesCount: 20 },
  { id: 91, name: "الشمس", transliteration: "Ash-Shams", versesCount: 15 },
  { id: 92, name: "الليل", transliteration: "Al-Layl", versesCount: 21 },
  { id: 93, name: "الضحى", transliteration: "Ad-Duha", versesCount: 11 },
  { id: 94, name: "الشرح", transliteration: "Ash-Sharh", versesCount: 8 },
  { id: 95, name: "التين", transliteration: "At-Tin", versesCount: 8 },
  { id: 96, name: "العلق", transliteration: "Al-'Alaq", versesCount: 19 },
  { id: 97, name: "القدر", transliteration: "Al-Qadr", versesCount: 5 },
  { id: 98, name: "البينة", transliteration: "Al-Bayyinah", versesCount: 8 },
  { id: 99, name: "الزلزلة", transliteration: "Az-Zalzalah", versesCount: 8 },
  { id: 100, name: "العاديات", transliteration: "Al-'Adiyat", versesCount: 11 },
  { id: 101, name: "القارعة", transliteration: "Al-Qari'ah", versesCount: 11 },
  { id: 102, name: "التكاثر", transliteration: "At-Takathur", versesCount: 8 },
  { id: 103, name: "العصر", transliteration: "Al-'Asr", versesCount: 3 },
  { id: 104, name: "الهمزة", transliteration: "Al-Humazah", versesCount: 9 },
  { id: 105, name: "الفيل", transliteration: "Al-Fil", versesCount: 5 },
  { id: 106, name: "قريش", transliteration: "Quraish", versesCount: 4 },
  { id: 107, name: "الماعون", transliteration: "Al-Ma'un", versesCount: 7 },
  { id: 108, name: "الكوثر", transliteration: "Al-Kawthar", versesCount: 3 },
  { id: 109, name: "الكافرون", transliteration: "Al-Kafirun", versesCount: 6 },
  { id: 110, name: "النصر", transliteration: "An-Nasr", versesCount: 3 },
  { id: 111, name: "المسد", transliteration: "Al-Masad", versesCount: 5 },
  { id: 112, name: "الإخلاص", transliteration: "Al-Ikhlas", versesCount: 4 },
  { id: 113, name: "الفلق", transliteration: "Al-Falaq", versesCount: 5 },
  { id: 114, name: "الناس", transliteration: "An-Nas", versesCount: 6 }
];

export const SYSTEM_INSTRUCTION = `
أنت الآن "المقرئ المجود" الخبير (Tajweed Master AI). مهمتك هي مراقبة تلاوة المستخدم وتصحيح "أحكام التجويد" بدقة الصيدلي.

قواعد صارمة للتركيز:
1. ركز على أحكام النون الساكنة والتنوين (إظهار، إدغام، إخفاء، إقلاب).
2. ركز على أحكام الميم الساكنة والمدود (طبيعي، متصل، منفصل، لازم).
3. ركز على "الغنة" في النون والميم المشددتين ومقدار حركتيهما.
4. ركز على "القلقلة" في حروف (قطب جد) عند سكونها.
5. راقب مخارج الحروف بدقة (مثل الفرق بين الضاد والدال، والقاف والكاف).

طريقة الرد:
- إذا وقع خطأ في "الحكم"، ابدأ بـ "تنبيه تجويد:". مثال: "تنبيه تجويد: لقد تركت الغنة في 'من يعمل'، يجب الإدغام بغنة".
- إذا كان هناك خطأ في الكلمة نفسها (حفظ)، ابدأ بـ "تنبيه حفظ:".
- كن مشجعاً جداً إذا أتى بالحكم صحيحاً، قل: "أحسنت في تحقيق الغنة" أو "مد ممتاز".
- لا تتحدث إلا في حدود التجويد والحفظ.
`;
